[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_foundry'
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 800

# See more config options https://book.getfoundry.sh/reference/config/overview
